version: "3.3"

services:
  locktutorialdb:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - locktutorial:/var/lib/postgresql/data
volumes:
  locktutorial:
